# Site settings
title: Nick codes 
header-img: img/home-bg.png
email: nickmidspace@gmail.com
copyright_name: Nicksalmon
description: > # this means to ignore newlines until "baseurl:"
  Come with us on now on a journey Through time and space...
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: nicksalmon
github_username:  Nicksalmon
learn_profile: Nicksalmon
email_username: nickmidspace@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
